include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    annotate_overrides: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    sort_child_properties_last: ignore
    unnecessary_this: ignore
    use_build_context_synchronously: ignore
