name: newsapp_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0
  dropdown_flutter: ^1.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  http: ^1.2.2
  icons_launcher: ^3.0.0
  intl: ^0.19.0
  share: ^2.0.4
  share_plus: ^10.1.2
  shimmer: ^3.0.0
  social_share: ^2.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

icons_launcher:
  image_path: "assets/Beritacepat.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
